databases:
  - name: user-management-db
    plan: free
    databaseName: user_management_db
    user: user_management

services:
  - type: web
    name: user-management-api
    runtime: docker
    plan: free
    repo: https://github.com/komal2605-2026/playground
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: /app/entrypoint.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: user-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
